lb:CConHash.o CHashFun.o CMd5.o CMD5HashFun.o CNode_s.o CVirtualNode_s.o CRBTree.o
	g++ -o lb Main.cpp CConHash.o CHashFun.o CMd5.o CMD5HashFun.o CNode_s.o CVirtualNode_s.o
	
CConHash.o:CConHash.cpp CConHash.h 
	g++ -c CConHash.cpp
	
CHashFun.o:CHashFun.cpp CHashFun.h
	g++ -c CHashFun.cpp
	
CMd5.o:CMd5.cpp  CMd5.h
	g++ -c CMd5.cpp
	
CMD5HashFun.o:CMD5HashFun.cpp CMD5HashFun.h
	g++ -c CMD5HashFun.cpp

CNode_s.o:CNode_s.cpp CNode_s.h
	g++ -c CNode_s.cpp
		
CVirtualNode_s.o:CVirtualNode_s.cpp CVirtualNode_s.h
	g++ -c CVirtualNode_s.cpp
CRBTree.o:CRBTree.cpp CRBTree.h
	g++ -c CRBTree.cpp	
	
